//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public string RegionID { get; set; }
        public string CountryID { get; set; }
        public string CompanyID { get; set; }
        public string BuildingID { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string Address5 { get; set; }
        public string PostalCode { get; set; }
        public Nullable<decimal> TotalArea { get; set; }
        public Nullable<long> Colour { get; set; }
    }
}
