//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FMDBEntities : DbContext
    {
        public FMDBEntities()
            : base("name=FMDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AlertMessage> AlertMessage { get; set; }
        public DbSet<AssetMaster> AssetMaster { get; set; }
        public DbSet<Building> Building { get; set; }
        public DbSet<CompanyMaster> CompanyMaster { get; set; }
        public DbSet<Country> Country { get; set; }
        public DbSet<EmployeeDepartment> EmployeeDepartment { get; set; }
        public DbSet<Floor> Floor { get; set; }
        public DbSet<InventoryMaster> InventoryMaster { get; set; }
        public DbSet<ItemGroup> ItemGroup { get; set; }
        public DbSet<Location> Location { get; set; }
        public DbSet<MAContract> MAContract { get; set; }
        public DbSet<MaintenanceTeam> MaintenanceTeam { get; set; }
        public DbSet<Menu> Menu { get; set; }
        public DbSet<Module> Module { get; set; }
        public DbSet<ModulePage> ModulePage { get; set; }
        public DbSet<Region> Region { get; set; }
        public DbSet<ServiceRequest> ServiceRequest { get; set; }
        public DbSet<ShopInfo> ShopInfo { get; set; }
        public DbSet<SRInvoice> SRInvoice { get; set; }
        public DbSet<SRStatus> SRStatus { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<UserActivities> UserActivities { get; set; }
        public DbSet<UserLogin> UserLogin { get; set; }
        public DbSet<UserRole> UserRole { get; set; }
        public DbSet<UserRoleAccess> UserRoleAccess { get; set; }
        public DbSet<VendorMaster> VendorMaster { get; set; }
        public DbSet<Zone> Zone { get; set; }
    }
}
