//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryMaster
    {
        public string BuildingID { get; set; }
        public string ItemCode { get; set; }
        public short ItemType { get; set; }
        public string Description { get; set; }
        public string UOM { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> BalanceQty { get; set; }
        public Nullable<decimal> AverageCost { get; set; }
        public Nullable<decimal> BalanceValue { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<short> ItemGroupID { get; set; }
    }
}
