//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAContract
    {
        public string BuildingID { get; set; }
        public string ContractNo { get; set; }
        public string Description { get; set; }
        public string AssetID { get; set; }
        public string ContractStart { get; set; }
        public string ContractEnd { get; set; }
        public string PreviousContractNo { get; set; }
        public Nullable<short> MaintenanceStatus { get; set; }
        public Nullable<short> ContractStatus { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> ContractAmount { get; set; }
        public Nullable<short> MaintenanceCycle { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedBy { get; set; }
    }
}
