//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public string MenuItemId { get; set; }
        public string MenuItem { get; set; }
        public string Menu_Role_Access { get; set; }
        public string MenuUrl { get; set; }
        public Nullable<short> IsActive { get; set; }
        public string MenuLevel { get; set; }
        public string ParentId { get; set; }
    }
}
