//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModulePage
    {
        public string PageID { get; set; }
        public int ModuleID { get; set; }
        public string PageDisplayText { get; set; }
        public string PageOrder { get; set; }
        public string ParentId { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string PageQuerystring { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> IsActive { get; set; }
    }
}
