//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequest
    {
        public string SRNo { get; set; }
        public short SRType { get; set; }
        public string RequestDate { get; set; }
        public string RequestedBy { get; set; }
        public short SRStatusID { get; set; }
        public string LocationID { get; set; }
        public string FloorID { get; set; }
        public string ShopName { get; set; }
        public string UnitNo { get; set; }
        public Nullable<long> TeamID { get; set; }
        public string AssetID { get; set; }
        public string Feedback { get; set; }
        public string AssignedTo { get; set; }
        public string AssignDate { get; set; }
        public string ResolvedBy { get; set; }
        public string ResolveDate { get; set; }
        public string ClosedDate { get; set; }
        public string ReopenDate { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> TotalChargeAmount { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CreateBy { get; set; }
        public string LastModifiedBy { get; set; }
        public string ReopenBy { get; set; }
        public string BuildingID { get; set; }
        public string Email { get; set; }
        public string ContactNumber { get; set; }
    }
}
