//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopInfo
    {
        public string ShopID { get; set; }
        public string ShopName { get; set; }
        public string BuildingID { get; set; }
        public string FloorID { get; set; }
        public string TenantCompanyName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string LastModifiedBy { get; set; }
        public string UnitNumber { get; set; }
    }
}
