//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserActivities
    {
        public long ID { get; set; }
        public System.DateTime ActivityDateTimeStamp { get; set; }
        public string ActivityDate { get; set; }
        public string ActivityTime { get; set; }
        public string UserID { get; set; }
        public string UserComputerName { get; set; }
        public string UserIPAddress { get; set; }
        public string UserAction { get; set; }
        public string Remarks { get; set; }
    }
}
