//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorMaster
    {
        public string VendorID { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string Address5 { get; set; }
        public string PostalCode { get; set; }
        public string ContactName { get; set; }
        public string ContactNumber { get; set; }
        public string Email1 { get; set; }
        public string ContactName2 { get; set; }
        public string ContactNumber2 { get; set; }
        public string Email2 { get; set; }
        public string ContactName3 { get; set; }
        public string ContactNumber3 { get; set; }
        public string Email3 { get; set; }
        public string Fax { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CreatedBy { get; set; }
        public string LastModifiedBy { get; set; }
    }
}
