//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zone
    {
        public string BuildingID { get; set; }
        public string ZoneID { get; set; }
        public string Description { get; set; }
        public Nullable<long> Colour { get; set; }
    }
}
